# Generated by Django 3.2.10 on 2023-06-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=255)),
                ('aemail', models.CharField(max_length=50)),
                ('apassword', models.CharField(max_length=50)),
                ('capassword', models.CharField(max_length=50)),
            ],
        ),
    ]
