# Generated by Django 3.2.10 on 2023-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0002_adminreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('oldprice', models.CharField(max_length=255)),
                ('newprice', models.CharField(max_length=255)),
                ('pdescription', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product/')),
                ('catagory', models.CharField(max_length=255)),
            ],
        ),
    ]
