# Generated by Django 3.2.10 on 2023-07-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0003_product_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=250)),
                ('total', models.CharField(max_length=250)),
                ('status', models.CharField(default='pending', max_length=250)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapp.product_tab')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapp.signform')),
            ],
        ),
    ]
